export default {
  TAP_INPUT_MODE: 1,
  SWIPE_INPUT_MODE: 2,
  MULTIPLE_CHOICE_INPUT_MODE: 3,
  SLIDER_INPUT_MODE: 4,
  MINOR_SWIPE_INPUT_MODE: 5,
  TEXT_BOX_INPUT_MODE: 6,
  LIKERT_INPUT_MODE: 7,
  VAS_INPUT_MODE: 8,
  COGS_SWIPE_INPUT_MODE: 9,
  ELASTIC_PULL_INPUT_MODE: 10,
  COGS_ELASTIC_PULL_INPUT_MODE: 11,
}
